In [1]:
import pandas as pd
import numpy as np

In [2]:
book = pd.read_csv('/content/book.csv', encoding='latin-1')
book

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

In [3]:
book.columns

Index(['Unnamed: 0', 'User.ID', 'Book.Title', 'Book.Rating'], dtype='object')

In [4]:
df= book.iloc[:,1:]
df.rename(columns={'User.ID':'ID','Book.Title':'Book','Book.Rating':'Rating'}, inplace=True)
df

ID                                               Book  Rating
0     276726                                Classical Mythology       5
1     276729                                       Clara Callan       3
2     276729                               Decision in Normandy       6
3     276736  Flu: The Story of the Great Influenza Pandemic...       8
4     276737                             The Mummies of Urumchi       6
...      ...                                                ...     ...
9995  162121       American Fried: Adventures of a Happy Eater.       7
9996  162121                              Cannibal In Manhattan       9
9997  162121                    How to Flirt: A Practical Guide       7
9998  162121                                           Twilight       8
9999  162129                       Kids Say the Darndest Things       6

[10000 rows x 3 columns]

In [5]:
df['ID'].nunique()

2182

In [6]:
df['Book'].nunique()

9659

In [7]:
df['Rating'].nunique()

10

In [8]:
df.sort_values('ID')

ID                                               Book  Rating
2401       8                                              Wings       5
2400       8  The Western way: A practical guide to the West...       5
2399       8                            Ancient Celtic Romances       5
2402       8                                           Truckers       5
2405       8                                  The Art Of Celtia       7
...      ...                                                ...     ...
2395  278854      La crÃ³nica del PerÃº (CrÃ³nicas de AmÃ©rica)       7
2398  278854  Celtic Mythology (Library of the World's Myths...       8
2393  278854                         A corrente de Trewis Scott       7
2394  278854                                      As valkÃ­rias       7
2397  278854     A Treasury of Irish Myth, Legend, and Folklore       6

[10000 rows x 3 columns]

In [9]:
newtable = df.pivot_table(index="ID", columns="Book",values="Rating",aggfunc='sum')
newtable

Book     Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
ID                                                                         
8                        NaN                                         NaN   
9                        NaN                                         NaN   
10                       NaN                                         NaN   
12                       NaN                                         NaN   
14                       NaN                                         NaN   
...                      ...                                         ...   
278846                   NaN                                         NaN   
278849                   NaN                                         NaN   
278851                   NaN                                         NaN   
278852                   NaN                                         NaN   
278854                   NaN                                         NaN   

Book     Repairing PC Drives &amp  '48  \
ID                                       
8                             NaN  NaN   
9                             NaN  NaN   
10                            NaN  NaN   
12                            NaN  NaN   
14                            NaN  NaN   
...                           ...  ...   
278846                        NaN  NaN   
278849                        NaN  NaN   
278851                        NaN  NaN   
278852                        NaN  NaN   
278854                        NaN  NaN   

Book    'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
ID                                                                              
8                                                     NaN                       
9                                                     NaN                       
10                                                    NaN                       
12                                                    NaN                       
14                                                    NaN                       
...                                                   ...                       
278846                                                NaN                       
278849                                                NaN                       
278851                                                NaN                       
278852                                                NaN                       
278854                                                NaN                       

Book    ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
ID                                                                     
8                                                     NaN              
9                                                     NaN              
10                                                    NaN              
12                                                    NaN              
14                                                    NaN              
...                                                   ...              
278846                                                NaN              
278849                                                NaN              
278851                                                NaN              
278852                                                NaN              
278854                                                NaN              

Book    01-01-00: A Novel of the Millennium  \
ID                                            
8                                       NaN   
9                                       NaN   
10                                      NaN   
12                                      NaN   
14                                      NaN   
...                                     ...   
278846                                  NaN   
278849                                  NaN   
278

In [10]:
newtable.fillna(0, inplace=True)
newtable

Book     Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
ID                                                                         
8                        0.0                                         0.0   
9                        0.0                                         0.0   
10                       0.0                                         0.0   
12                       0.0                                         0.0   
14                       0.0                                         0.0   
...                      ...                                         ...   
278846                   0.0                                         0.0   
278849                   0.0                                         0.0   
278851                   0.0                                         0.0   
278852                   0.0                                         0.0   
278854                   0.0                                         0.0   

Book     Repairing PC Drives &amp  '48  \
ID                                       
8                             0.0  0.0   
9                             0.0  0.0   
10                            0.0  0.0   
12                            0.0  0.0   
14                            0.0  0.0   
...                           ...  ...   
278846                        0.0  0.0   
278849                        0.0  0.0   
278851                        0.0  0.0   
278852                        0.0  0.0   
278854                        0.0  0.0   

Book    'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
ID                                                                              
8                                                     0.0                       
9                                                     0.0                       
10                                                    0.0                       
12                                                    0.0                       
14                                                    0.0                       
...                                                   ...                       
278846                                                0.0                       
278849                                                0.0                       
278851                                                0.0                       
278852                                                0.0                       
278854                                                0.0                       

Book    ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
ID                                                                     
8                                                     0.0              
9                                                     0.0              
10                                                    0.0              
12                                                    0.0              
14                                                    0.0              
...                                                   ...              
278846                                                0.0              
278849                                                0.0              
278851                                                0.0              
278852                                                0.0              
278854                                                0.0              

Book    01-01-00: A Novel of the Millennium  \
ID                                            
8                                       0.0   
9                                       0.0   
10                                      0.0   
12                                      0.0   
14                                      0.0   
...                                     ...   
278846                                  0.0   
278849                                  0.0   
278

In [11]:
from sklearn.metrics import pairwise_distances

In [12]:
sim_user = 1 - pairwise_distances(newtable.values, metric="cosine")

In [13]:
sim_user

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [14]:
sim_user_df = pd.DataFrame(sim_user)
sim_user_df

0     1     2     3     4     5     6     7     8     9     ...  2172  \
0      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2177   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2178   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2179   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      2173  2174  2175  2176  2177  2178  2179  2180  2181  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2177   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0  
2178   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0  
2179   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  

[2182 rows x 2182 columns]

In [15]:
# chenging index of matris by user id

sim_user_df.columns = book['User.ID'].unique()
sim_user_df.index = book['User.ID'].unique()



In [16]:
sim_user_df.iloc[0:5, 0:5]

276726  276729  276736  276737  276744
276726     1.0     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0     0.0
276737     0.0     0.0     0.0     1.0     0.0
276744     0.0     0.0     0.0     0.0     1.0

In [17]:
#filling digonal values to zero
np.fill_diagonal(sim_user, 0)
sim_user_df.iloc[0:5, 0:5]

276726  276729  276736  276737  276744
276726     0.0     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0     0.0

# similar users

In [18]:
sim_user_df.idxmax(axis=1)[0:10]

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
276745    276726
276747    276726
276748    161677
276751    276726
276754    276726
dtype: int64

In [20]:
# Users similarity
book[(book['User.ID']==276726) | (book['User.ID']==276729)]

Unnamed: 0  User.ID            Book.Title  Book.Rating
0           1   276726   Classical Mythology            5
1           2   276729          Clara Callan            3
2           3   276729  Decision in Normandy            6

according to data we can suggest Clara Callan and Decision in Normandy books to user(276726) and Classical Mythology book to user(276729)

In [21]:
book[(book['User.ID']==276726) | (book['User.ID']==276744)]

Unnamed: 0  User.ID              Book.Title  Book.Rating
0           1   276726     Classical Mythology            5
5           6   276744  The Kitchen God's Wife            7

In [36]:
# Prediction

userA =book[(book['User.ID']==276729)]

userB =book[(book['User.ID']==276726)]

In [37]:
userA

Unnamed: 0  User.ID            Book.Title  Book.Rating
1           2   276729          Clara Callan            3
2           3   276729  Decision in Normandy            6

In [38]:
userB

Unnamed: 0  User.ID           Book.Title  Book.Rating
0           1   276726  Classical Mythology            5

In [39]:
book_userA = list(userA['Book.Title'])
book_userB = list(userB['Book.Title'])


In [40]:
for mov in book_userA:
  if mov not in book_userB:
    print("Recommendations =", mov)

Recommendations = Clara Callan
Recommendations = Decision in Normandy


Those are Recommended books for userB